### ISSUE TITLE
Upgrade to LaxarJS v2

### ISSUE THREAD

**Issue by x1B** [LaxarJS/finder-demo#18]
Upgrade the demo project to a examplary LaxarJS v2 project.

**Comment by jonaswjs** [comment]
### BREAKING CHANGE

Removed `omdb-search-widget` because the API isn't free anymore:
http://www.omdbapi.com/
> 05/08/17 - Going Private! Please go read the post on the Patreon page about this major change. 

Removed `open-weather-map-widget` because the access to the API is restricted now:
http://openweathermap.org/faq#error401
> A: Starting from 9 October 2015 our API requires a valid APPID for access.

The `open-street-map-widget` doesn't use `MapQuest` anymore because the access is restricted now:
https://lists.openstreetmap.org/pipermail/talk/2016-June/076106.html

**Comment by jonaswjs** [comment]
Implemented on `master` (`v1.6.0`).
